//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormSDB.WcfServiceSDB {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfServiceSDB.IServiceSDB")]
    public interface IServiceSDB {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSDB/GetClientInfo", ReplyAction="http://tempuri.org/IServiceSDB/GetClientInfoResponse")]
        System.Data.DataSet GetClientInfo(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSDB/GetClientInfo", ReplyAction="http://tempuri.org/IServiceSDB/GetClientInfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetClientInfoAsync(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSDB/GetBook", ReplyAction="http://tempuri.org/IServiceSDB/GetBookResponse")]
        System.Data.DataSet GetBook(int statusReading, string language, string name, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSDB/GetBook", ReplyAction="http://tempuri.org/IServiceSDB/GetBookResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetBookAsync(int statusReading, string language, string name, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSDB/GetClientStatistics", ReplyAction="http://tempuri.org/IServiceSDB/GetClientStatisticsResponse")]
        System.Data.DataSet GetClientStatistics(string statusSubscription, string language, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSDB/GetClientStatistics", ReplyAction="http://tempuri.org/IServiceSDB/GetClientStatisticsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetClientStatisticsAsync(string statusSubscription, string language, string address);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceSDBChannel : WinFormSDB.WcfServiceSDB.IServiceSDB, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSDBClient : System.ServiceModel.ClientBase<WinFormSDB.WcfServiceSDB.IServiceSDB>, WinFormSDB.WcfServiceSDB.IServiceSDB {
        
        public ServiceSDBClient() {
        }
        
        public ServiceSDBClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSDBClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSDBClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSDBClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetClientInfo(string address) {
            return base.Channel.GetClientInfo(address);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetClientInfoAsync(string address) {
            return base.Channel.GetClientInfoAsync(address);
        }
        
        public System.Data.DataSet GetBook(int statusReading, string language, string name, string address) {
            return base.Channel.GetBook(statusReading, language, name, address);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetBookAsync(int statusReading, string language, string name, string address) {
            return base.Channel.GetBookAsync(statusReading, language, name, address);
        }
        
        public System.Data.DataSet GetClientStatistics(string statusSubscription, string language, string address) {
            return base.Channel.GetClientStatistics(statusSubscription, language, address);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetClientStatisticsAsync(string statusSubscription, string language, string address) {
            return base.Channel.GetClientStatisticsAsync(statusSubscription, language, address);
        }
    }
}
